=== hongyiweiwu/latex_ps_gen/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "latex-ps-gen/schema",
    "title": "latex-ps-gen Config File",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "courseTitle": {
            "type": "string"
        },
        "author": {
            "type": "string"
        },
        "psNumberingScheme": {
            "enum": [
                "roman",
                "arabic"
            ]
        },
        "packages": {
            "type": "array"
        },
        "questionNumberingScheme": {
            "anyOf": [
                {
                    "properties": {
                        "scheme": {
                            "const": "enumerate",
                            "type": "string"
                        },
                        "format": {
                            "type": "string"
                        }
                    }
                }, {
                    "properties": {
                        "scheme": {
                            "const": "description"
                        }
                    }
                }
            ]
        }
    }
}

=== hongyiweiwu/latex_ps_gen/examples/enumerate_scheme.json
{
    "$schema": "/Users/yi/Documents/Repo.nosync/latex_ps_gen/schema.json",
    "courseTitle": "Quantum Mechanics II",
    "author": "Yi Hong",
    "psNumberingScheme": "roman",
    "questionNumberingScheme": {
        "scheme": "enumerate",
        "format": "\\textbf{Problem \\arabic*}"
    },
    "packages": [
        "amsmath",
        "amssymb",
        "braket"
    ]
}

=== hongyiweiwu/latex_ps_gen/examples/description_scheme.json
{
    "$schema": "/Users/yi/Documents/Repo.nosync/latex_ps_gen/schema.json",
    "courseTitle": "Honors Analysis II",
    "author": "Kavya Tumkur",
    "psNumberingScheme": "roman",
    "questionNumberingScheme": {
        "scheme": "description"
    },
    "packages": [
        "amsmath",
        "amssymb"
    ]
}
